



--- SELECT : PERMITE PESQUISAR E VISUALIZAR DADOS DE UMA VISÃO (VIEW), TABELA OU COLUNA
/*
 comando select recupera os dados de uma ou mais tabelas, 
 sendo um dos comandos mais simples e, ao mesmo tempo, 
 mais extenso da SQL devido as suas funções, operandos, c
 omandos, sub-comandos e cláusulas não obrigatórias.
  


*/

-- SELECT EM TODA TABELA: MUITO CUIDADO AO USAR O SELECT * FROM TABELA, POIS VOCÊ PODE TRAVAR A TABELA OU A BASE DEPENDENDO DO NÚMERO DE REGISTROS
SELECT * FROM RODCLI

-- SELECT DE UM ÚNICO REGISTRO DA TABELA
SELECT TOP 1 * FROM RODCLI

-- SELECT DE UM ÚNICO REGISTRO DA TABELA, PORÉM TRAZENDO AS COLUNAS QUE SE QUER CONSULTAR
SELECT TOP 1 CODCLIFOR, RAZSOC, CODCGC FROM RODCLI

-- SELECT TRAZENDO AS 100 PRIMEIRAS LINHAS DA TABELA
SELECT TOP 100 * FROM RODCLI 

-- SELECT TRAZENDO AS 100 PRIMEIRAS LINHAS DA TABELA, PORÉM INCLUIDO UMA CONDIÇÃO WHERE PARA ESPECIFICAR AS LINHAS QUE SERÃO CONSULTADAS
SELECT TOP 100 * FROM RODCLI WHERE CODCGR = 1

-- SELECT TRAZENDO AS 100 PRIMEIRAS LINHAS DA TABELA, PORÉM USANDO O ORDER BY PARA ESCOLHER A ORDENAÇÃO
SELECT TOP 100 DATINC, CODCLIFOR, RAZSOC
FROM RODCLI 
ORDER BY RODCLI.DATINC DESC

SELECT TOP 100 DATINC, CODCLIFOR, RAZSOC
FROM RODCLI 
ORDER BY RAZSOC ASC

---SELECT PARA TRAZER DADOS DE UMA CONDIÇÃO ENTRE DOIS VALORES

SELECT RODCLI.DATINC, * 
FROM RODCLI
WHERE RODCLI.DATINC BETWEEN '2018-01-01' AND '2018-01-31'

-- SELECT COM AND NA CONDIÇÃO WHERE
SELECT RODCLI.DATINC, * 
FROM RODCLI
WHERE RODCLI.DATINC >='2018-01-01' AND  RODCLI.DATINC <='2018-01-31'

-- SELECT COM OR NA CONDIÇÃO WHERE
SELECT RODCLI.DATINC, * 
FROM RODCLI
WHERE (CONVERT(DATE,RODCLI.DATINC) ='2018-01-01' OR  CONVERT(DATE,RODCLI.DATINC) ='2018-01-03')

--  SELECT COM IN

SELECT TOP 5 * FROM RODCON
WHERE RODCON.CODPAG IN (1,2)
AND RODCON.DATCAD BETWEEN '2018-01-01' AND '2018-01-20'

--- SELECT COM LIKE 

SELECT * FROM RODCLI
WHERE RODCLI.RAZSOC LIKE '%AGROPALMA%'

SELECT * FROM RODCLI
WHERE RODCLI.RAZSOC LIKE 'AGROPALMA%'

SELECT * FROM RODCLI
WHERE RODCLI.RAZSOC LIKE '%AGROPALMA'

-- SELECT COM NOT

SELECT TOP 5 * FROM RODCLI
WHERE NOT RODCLI.RAZSOC LIKE '%AGROPALMA'

--- SELECT ELIMINANDO DUPLICIDADES

SELECT DISTINCT  RODCON.CODCON FROM RODCON
WHERE RODCON.DATCAD BETWEEN '2018-01-01' AND '2018-01-20'



