/*

FUNÇÕES BÁSICAS

– invocação de funções de agregação
• COUNT (contador de ocorrências [de um atributo])
• MAX / MIN (valores máximo / mínimo de um atributo)
• SUM (somador de valores de um atributo)
• AVG (média de valores de um atributo)------------------------------------------------------OPERADORES DE FUNÇÕES BÁSICAS= --> ATRUBUI UM VALOR A UMA VARIÁVEL+ --> SOMA DOIS VALORES- --> SUBTRAI UM VALORES* --> MULTIPLICA DOIS VALORES/ --> DIVIDE UM VALOR POR OUTRO-------------------------------------------------------OPERADORES DE COMPARAÇÃO:>  --> MAIOR QUE<  --> MENOR QUE=  --> IGUAL<>  --> DIFERENTE>=  --> MAIOR OU IGUAL<=  --> MENOR OU IGUALLIKE  --> VERIFICA PARTE DE UM VALOR*/--- USO DO COUNT E DANDO ALIAS PARA UM CAMPO E UMA TABELASELECT COUNT(*) AS QTDEFROM ESTPED PEDWHERE PED.USUINC LIKE '%BRUNA%'AND YEAR(PED.DATINC) = 2018--- USO DO GROUP BYSELECT ESTPED.USUINC, COUNT(*) AS QTDEFROM ESTPED WHERE YEAR(ESTPED.DATINC) = 2018GROUP BY ESTPED.USUINCORDER BY COUNT(*) DESC-- USO DO MAXSELECT ESTPED.USUINC, MAX(ESTPED.DATINC) AS DATA_MAXIMAFROM ESTPEDWHERE YEAR(ESTPED.DATINC) = 2018GROUP BY ESTPED.USUINC-- USO DO MINSELECT ESTPED.USUINC, MIN(ESTPED.DATINC) AS DATA_MINIMAFROM ESTPEDWHERE YEAR(ESTPED.DATINC) = 2018GROUP BY ESTPED.USUINC--- USO DO SUMSELECT ESTPED.USUINC, SUM(ESTPED.VLRTOT) AS VALOR_TOTALFROM ESTPEDWHERE YEAR(ESTPED.DATINC) = 2018GROUP BY ESTPED.USUINC-- USO DO AVGSELECT ESTPED.USUINC, AVG(ESTPED.VLRTOT) AS VALOR_MEDIOFROM ESTPEDWHERE YEAR(ESTPED.DATINC) = 2018GROUP BY ESTPED.USUINC