
-- PARA VER O RESULTADO DA FUNÇÃO SELECT DBO.SI_FN_RECDOC_TESTE(6,4,2018)  -->O CONTEUDO DENTRO DOS PARANTESES SÃO OS PARAMETROS

 CREATE FUNCTION [dbo].[SI_FN_RECDOC_TESTE](@PCODEMP INT, @PMES INT, @PANO INT) RETURNS DECIMAL(16,2)
 
/*
CRIADO POR NILZA - EM 20/04/2015 - SOLICITADO POR ELIAS - CHAMADO: 50108


*/
BEGIN
	DECLARE @SALDO AS DECIMAL(16,2)

	RETURN	 
		( 
 
 
			 SELECT 

			COALESCE(SUM(SUB.SALDO),0)AS VALOR
 
			 FROM
 
			 (
 
			 SELECT DISTINCT 
			 RECMEN.CODFIL,
			 RECMEN.NUMDUP,
			 (COALESCE(RECDOCI.VLRLIQ,0) - COALESCE(RECDOCI.VLRREC,0) - COALESCE(RECDOC.DESCAN,0)) AS SALDO

			 FROM   RECDOCI RECDOCI INNER JOIN RECDOC ON RECDOCI."NUMDUP" = RECDOC."NUMDUP" AND RECDOCI."CODFIL" = RECDOC."CODFIL"    
									LEFT OUTER JOIN RECMEN ON RECDOCI."NUMDUP" = RECMEN."NUMDUP" AND RECDOCI."CODFIL" = RECMEN."CODFIL"       
									INNER JOIN RODFIL ON  RECDOC."CODFIL" = RODFIL."CODFIL"
									LEFT OUTER JOIN RECRAT ON RECDOC."NUMDUP" = RECRAT."NUMDUP" AND RECDOC."CODFIL" = RECRAT."CODFIL"     
						  
 
			 WHERE  
			CONVERT(VARCHAR,"RECDOC"."DATEMI",103) < CONVERT(VARCHAR,GETDATE())  
			 AND (RECDOC.CODOPE IN (1,2,3,4,5,6,23))
			 AND RODFIL."CODEMP"=@PCODEMP 
			 AND ("RECDOCI"."SITUAC"='D' OR "RECDOCI"."SITUAC"='P') 
			 AND MONTH("RECDOCI"."DATVEN") = @PMES 
			 AND YEAR("RECDOCI"."DATVEN") = @PANO 




			 ) AS SUB
		 ) 

 END





GO


