
SELECT 
	SUB.LOCALI,
	SUM(QTDE) AS QTDE
FROM 
	(
	SELECT 
		CASE ESTIRL.CODLOC
			WHEN 36 THEN 'OBRAS' --LOCAL 1
			WHEN 46 THEN 'CONTRATOS' -- LOCAL 2
			WHEN 68 THEN 'CONTRATOS' --LOCAL 3
			WHEN 72 THEN 'OBRAS' -- LOCAL 4
			WHEN 55 THEN 'CONTRATOS' -- LOCAL 5
			WHEN 56 THEN 'OBRAS' -- LOCAL 6
			ELSE 'COMPRAS'
		END AS LOCALI,
		COUNT(*) AS QTDE

		FROM ESTIRL

		WHERE YEAR(ESTIRL.DATINC) = 2018

		GROUP BY ESTIRL.CODLOC

	) AS SUB

	GROUP BY SUB.LOCALI