CREATE TABLE TMP_TREINAMENTO_FAST 
(
TMP_ID INT IDENTITY,
TMP_NOME VARCHAR(100),
TMP_DATNAS SMALLDATETIME,
TMP_DATINC VARCHAR(20)
)

--- INSERT COM SELECT
INSERT TMP_TREINAMENTO_FAST
SELECT TOP 5 RODMOT.NOMMOT, ISNULL(RODMOT.DTNASC, '1900-01-01'), GETDATE(), NULL  FROM RODMOT

-- INSERT COM COLUNAS E DADOS DECLARADOS
INSERT TMP_TREINAMENTO_FAST (TMP_NOME, TMP_DATNAS, TMP_DATINC, TMP_USUINC) VALUES ('TESTE', '2019-01-01', GETDATE(), 'ADMIN')

-- INSERT COM WHERE 
INSERT TMP_TREINAMENTO_FAST
SELECT TOP 5 RODMOT.NOMMOT, ISNULL(RODMOT.DTNASC, '1900-01-01'), GETDATE(), NULL  
FROM RODMOT
WHERE RODMOT.NOMMOT LIKE '%JOAO%'



--- SELECIONANDO OS DADOS E VERIFICANDO QUE A COLUNA TMP_DATINC ESTÁ ERRADA
SELECT * FROM TMP_TREINAMENTO_FAST

--- ALTERANDO O TIPO DE UMA COLUNA
ALTER TABLE TMP_TREINAMENTO_FAST ALTER COLUMN TMP_DATINC SMALLDATETIME

-- INCLUINDO UMA NOVA COLUNA
ALTER TABLE TMP_TREINAMENTO_FAST ADD  TMP_USUINC VARCHAR(100) DEFAULT 'ADMIN'

-- LIMPANDO DADOS COM DELETE E WHERE (MUITO CUIDADO COM ESSE COMANDO)
DELETE FROM TMP_TREINAMENTO_FAST WHERE TMP_ID = 5

-- LIMPANDO DADOS SEM WHERE (MUITO CUIDADO COM ESSE COMANDO)
DELETE FROM TMP_TREINAMENTO_FAST

--- OBS: QUANDO SE USA O COMANDO DELETE EM UMA TABELA COM AUTO INCREMENTO, OS PRÓXIMOS DADOS A SEREM INSERIDOS, SEGUIRÃO DE ACORDO COM O ÚLTIMO ID
INSERT TMP_TREINAMENTO_FAST
SELECT TOP 5 RODMOT.NOMMOT, ISNULL(RODMOT.DTNASC, '1900-01-01'), GETDATE(), NULL  FROM RODMOT

SELECT * FROM TMP_TREINAMENTO_FAST

--- USANDO O TRUNCATE PARA LIMPAR UMA TABELA (MUITO CUIDADO COM ESSE COMANDO)
-- O TRUNCATE "RESETA" O AUTO INCREMENTO E AS NOVAS INCLUSÕES PARTIRÃO DO NÚMERO 1

TRUNCATE TABLE TMP_TREINAMENTO_FAST

INSERT TMP_TREINAMENTO_FAST
SELECT TOP 5 RODMOT.NOMMOT, ISNULL(RODMOT.DTNASC, '1900-01-01'), GETDATE(), NULL  FROM RODMOT

SELECT * FROM TMP_TREINAMENTO_FAST

--- CRIANDO UM BACKUP DA TABELA COM "SELECT INTO"

SELECT  * INTO  TMP_TREINAMENTO_FAST_24022019 FROM TMP_TREINAMENTO_FAST

-- EXCLUINDO UMA TABELA
DROP TABLE TMP_TREINAMENTO_FAST_24022019

