/*
UPDATE

-- USE DB_VISUAL_RODOPAR_21082018 --> FORÇA O USO DO BANCO DE DADOS
--BEGIN TRANSACTION  --> ABRE UMA TRANSAÇÃO
--COMMIT --> FINALIZA A TRANSAÇÃO QUE FOI ALTERADA
--ROLLBACK  --> CANCELA UMA TRANSAÇÃO ALTERADA
*/


USE DB_VISUAL_RODOPAR_21082018

-- SELECT * FROM TMP_TREINAMENTO_FAST

BEGIN TRANSACTION

UPDATE TMP_TREINAMENTO_FAST SET TMP_DATNAS = '1995-01-01' WHERE TMP_ID = 1

COMMIT

-- OU

ROLLBACK


-- PARA ENCONTRAR A CONFIGURAÇÃO DE UMA TABELA
SP_HELP TMP_TREINAMENTO_FAST



