/*
FUNÇÕES PARA MANIPULAÇÃO DE STRING

*/

-- SUBSTRING
SELECT SUBSTRING(RAZSOC, 1,7), RAZSOC, * FROM RODCLI WHERE CODCLIFOR = 1


-- LEFT 
SELECT LEFT(RAZSOC, 7), RAZSOC, * FROM RODCLI WHERE CODCLIFOR = 1

-- RIGHT 
SELECT RIGHT(RAZSOC, 7), RAZSOC, * FROM RODCLI WHERE CODCLIFOR = 1

-- UPPER
SELECT UPPER(ENDERE), ENDERE, * FROM RODCLI WHERE CODCLIFOR = 1

-- LOWER
SELECT LOWER(ENDERE), ENDERE, * FROM RODCLI WHERE CODCLIFOR = 1

-- REPLACE
SELECT REPLACE(CODCGC, '-', ''), CODCGC, * FROM RODCLI WHERE CODCLIFOR = 1

SELECT REPLACE(REPLACE(CODCGC, '-', ''), '.', ''), CODCGC, * FROM RODCLI WHERE CODCLIFOR = 1


-- REVERSE
SELECT REVERSE(ENDERE), ENDERE, * FROM RODCLI WHERE CODCLIFOR = 1

-- LTRIM / RTRIM
SELECT LTRIM(ENDERE), ENDERE, * FROM RODCLI WHERE CODCLIFOR = 1
SELECT RTRIM(ENDERE), ENDERE, * FROM RODCLI WHERE CODCLIFOR = 1

-- STUFF 

SELECT STUFF(RAZSOC, 10, 10, 'TESTE') FROM RODCLI WHERE CODCLIFOR = 1

-- CEILING 
SELECT CEILING(CONVERT(DECIMAL(10,2),10 /CONVERT(DECIMAL(10,2),4) ))

-- ROUND 
SELECT ROUND(CONVERT(DECIMAL(10,2),10 /CONVERT(DECIMAL(10,2),3) ),2,2)


-- DATEDD
SELECT DATEADD(DAY, 4, GETDATE())

SELECT DATEADD(DAY, -4, GETDATE())

-- DATEDIFF

SELECT DATEDIFF(DAY, GETDATE(),(DATEADD(DAY, 4, GETDATE())))

-- MONTH
SELECT MONTH(GETDATE())

--DATEPART

SELECT DATEPART(DAY, GETDATE())
SELECT DATEPART(MONTH, GETDATE())
SELECT DATEPART(YEAR, GETDATE())
SELECT DATEPART(WEEK, GETDATE())
SELECT DATEPART(WEEKDAY, GETDATE())
SELECT DATEPART(HOUR, GETDATE())
SELECT DATEPART(MINUTE, GETDATE())
SELECT DATEPART(SECOND, GETDATE())

-- DATENAME
SELECT DATENAME(MONTH, GETDATE())

-- CAST E CONVERT

SELECT CAST(GETDATE() AS DATE)

SELECT CONVERT(VARCHAR, GETDATE() , 103)
SELECT CONVERT(VARCHAR, GETDATE() , 106)