/*

INNER JOIN
LEFT OUTER JOIN


*/

-- TEM OBRIGATORIAMENTE O DADO RELACIONADO ENTRE AS DUAS TABELAS
SELECT COUNT(*)

FROM RODCLI INNER JOIN RODCGR ON RODCLI.CODCGR = RODCGR.CODCGR



-- TEM NA PRIMEIRA TABELA, MAS NÃO OBRIGATORIAMENTE NA SEGUNDA
SELECT COUNT(*)

FROM RODCLI LEFT OUTER JOIN RODCGR ON RODCLI.CODCGR = RODCGR.CODCGR