/*

EXEMPLO DE CRIAÇÃO DE VIEWS

*/



USE db_visual_rodopar_21082018 --> FORÇA A IDENTIFICAÇÃO DO BANCO QUE SERÁ CRIADO OU ALTERADO ALGUM OBJETO

CREATE VIEW SI_VW_TREINAMENTO_1 AS --> USO DO COMANDO CREATE --> POR PADRÃO, TODAS AS NOSSA VW´S INICIAM COM SI_VW_TABELA PARA FACILITAR A SUA IDENTIFICAÇÃO

/* IMPORTANTE O USO DE COMENTÁRIOS PARA INFORMAR DATA DE CRIAÇÃO / ANALISTA DE CRIAÇÃO / SOLICITANTE / CHAMADO */


-- 1 INFORME SEMPRE OS CAMPOS QUE DESEJA TRAZER NO SELECT
SELECT 
	R.CODFIL, 
	R.SERCON,
	R.CODCON,
	C.CODCLIFOR,
	C.RAZSOC

FROM RODCON R LEFT OUTER JOIN RODCLI C ON --> O USO DE ALIAS FACILITA A DIGITAÇÃO DA TABELA X CAMPO
								R.CODPAG = C.CODCLIFOR
WHERE R.SITUAC <> 'C' --> IDENTIFIQUE SEMPRE AS CONDIÇÕES NECESSÁRIAS PARA A CRIAÇÃO DO OBJETO, COMO: SITUAÇÃO DO DOCUMENTO / TIPO / PERIODO ENTRE OUTRAS INFORMAÇÕES NECESSÁRIAS


--=========================================================================================================================
-- ALTERAÇÃO DE VW
--OBSERVAÇÃO --> VOCÊ SÓ CONSEGUE USAR ORDER BY EM VW´S QUANDO O SELECT ESTÁ COM O COMANDO PERCENT 100

GO --> QUANDO VC TEM VÁRIOS SCRIPTS EM UM MESMO ARQUIVO, O GO VAI FAZER VC SEGUIR PARA A PRÓXIMA ETAPA


ALTER VIEW SI_VW_TREINAMENTO_1 AS --> USO DO COMANDO ALTER PARA REALIZAR ALTERAÇÃO DE UMA VW

/* IMPORTANTE O USO DE COMENTÁRIOS PARA INFORMAR DATA DE CRIAÇÃO / ANALISTA DE CRIAÇÃO / SOLICITANTE / CHAMADO 


*/

-- 1 INFORME SEMPRE OS CAMPOS QUE DESEJA TRAZER NO SELECT
SELECT TOP (100) PERCENT 
	R.CODFIL, 
	R.SERCON,
	R.CODCON,
	C.CODCLIFOR,
	C.RAZSOC

FROM RODCON R LEFT OUTER JOIN RODCLI C ON --> O USO DE ALIAS FACILITA A DIGITAÇÃO DA TABELA X CAMPO
								R.CODPAG = C.CODCLIFOR
WHERE R.SITUAC <> 'C' --> IDENTIFIQUE SEMPRE AS CONDIÇÕES NECESSÁRIAS PARA A CRIAÇÃO DO OBJETO, COMO: SITUAÇÃO DO DOCUMENTO / TIPO / PERIODO ENTRE OUTRAS INFORMAÇÕES NECESSÁRIAS

ORDER BY R.DATCAD DESC
--OBSERVAÇÃO --> VOCÊ SÓ CONSEGUE USAR ORDER BY EM VW´S QUANDO O SELECT ESTÁ COM O TOP (100) PERCENT 




----------------USO DO UNION --> PRECISA TER A MESMA QUANTIDADE DE COLUNAS E TIPOS IGUAIS ENTRE OS DOIS BLOCOS---------------------------------------------

SELECT TOP 10
	'CTE' AS TIPO,
	R.CODFIL, 
	R.SERCON,
	R.CODCON,
	C.CODCLIFOR,
	C.RAZSOC


FROM RODCON R LEFT OUTER JOIN RODCLI C ON --> O USO DE ALIAS FACILITA A DIGITAÇÃO DA TABELA X CAMPO
								R.CODPAG = C.CODCLIFOR
WHERE R.SITUAC <> 'C'

UNION ALL

SELECT TOP 10
	'NF' AS TIPO,
	R.CODFIL, 
	R.SERSUB,
	R.CODIGO,
	C.CODCLIFOR,
	C.RAZSOC


FROM ESTNOT R LEFT OUTER JOIN RODCLI C ON --> O USO DE ALIAS FACILITA A DIGITAÇÃO DA TABELA X CAMPO
								R.CODCLIFOR = C.CODCLIFOR
WHERE R.SITUAC <> 'C'