/*
USO DE VÁRIAVEIS E TABELAS TEMPORÁRIAS
*/

DECLARE @PANO INT --> DECLARAÇÃO DE VARIÁVEL

SET @PANO = 2018 --> DANDO UM VAOR PARA VARIAVEL

SELECT @PANO --> EXIBINDO O CONTEÚDO DA VARIÁVEL

-------------------------------------------------------------------------------
-- 1 DECALRADO VARIAVEIS
DECLARE @PANO INT --> DECLARAÇÃO DE VARIÁVEL
SET @PANO = 2018 --> DANDO UM VAOR PARA VARIAVEL

-- CRIADO TABELA TEMPORÁRIA
-- O USO # NA FRENTE DA TABELA INFORMA QUE ELA SERÁ USADA LOCALMENTE


CREATE TABLE #TMP_TESTE_1
(
TID INT,
TNOME VARCHAR(100),
TDATCAD SMALLDATETIME
)


INSERT #TMP_TESTE_1 VALUES (1, 'TESTE 1', '2019-01-01')
INSERT #TMP_TESTE_1 VALUES (1, 'TESTE 1', '2019-02-01')
INSERT #TMP_TESTE_1 VALUES (1, 'TESTE 1', '2019-02-01')
INSERT #TMP_TESTE_1 VALUES (1, 'TESTE 1', '2018-03-01')
INSERT #TMP_TESTE_1 VALUES (1, 'TESTE 1', '2018-03-01')
INSERT #TMP_TESTE_1 VALUES (1, 'TESTE 1', '2018-03-01')




SELECT * 
FROM #TMP_TESTE_1 T
WHERE YEAR(TDATCAD) = @PANO