/*
PROCEDURE COM VARIAVEIS

*/
ALTER PROCEDURE [dbo].[SI_SP_RODICT_CONTRATO_CLIENTE] (@PDATINI DATETIME, @PDATFIM DATETIME) AS
/* CRIADO POR NILZA EM 05/04/2017 - SOLICITADO POR GIOVANNI PARA CONTROLAR OS CONTRATOS DE LOCAÇÕES QUE NÃO TIVERAM FATURAMENTO NO PERÍODO - SERA USADO NO RELATÓRIO 210 */

SELECT 
	CTS.CODIGO AS CONTRATO,
	CLI.NOMEAB AS CLIENTE, 
	
	COUNT(*) QTDE_EQUIP_CTR,

	--- USO DE SUBQUERY ----
	(SELECT COUNT(DISTINCT PLACA2) FROM RODCON WHERE DATCAD >= @PDATINI AND DATCAD <=@PDATFIM AND SITUAC <> 'C' AND DATBAI IS NULL AND RODCON.CODPAG = CTS.CODCLIFOR) QTDE_EQUIP_UTI,
	CTS.DATFIN,
	MAX(DAY(ICT.DATINI)) AS DIA_FATURAMENTO,
	'CAMPO NOVO' AS TIPO


FROM RODICT ICT LEFT OUTER JOIN RODCTS  CTS WITH NOLOCK ON ICT.CODIGO = CTS.CODIGO
				LEFT OUTER JOIN RODCLI CLI  WITH NOLOCK ON CTS.CODCLIFOR = CLI.CODCLIFOR

WHERE 
	NOT CLI.CODCLIFOR IN (SELECT CODCLIFOR FROM RODDUP WHERE CODTAR = 528 AND RODDUP.DATEMI >=@PDATINI AND RODDUP.DATEMI <=@PDATFIM AND RODDUP.SITUAC <> 'C')
	AND CTS.DATINI >= @PDATINI
	AND CTS.DATFIN <= @PDATFIM

	AND ICT.SEMREB IS NOT NULL


GROUP BY CTS.CODIGO,CLI.NOMEAB, CTS.CODCLIFOR, CTS.DATFIN



GO


